SpamFilter: some i18n fixes
 - in captcha/expression.py, use `gettext` rather than `_` when applied to an expression rather than a string constant; they both do the same at runtime, but the former is not an extraction keyword
 - add a missing 'xmlns:i18n=... i18n:domain=...` line, in verify_captcha.html
 - restore usage of '%%' in admin_spammonitor.html, otherwise this leads to the following catalog compilation error:
{{{
running compile_catalog
error: tracspamfilter/locale\fr\LC_MESSAGES\tracspamfilter.po:1276: placeholders are incompatible
error: tracspamfilter/locale\fr\LC_MESSAGES\tracspamfilter.po:1281: placeholders are incompatible
error: tracspamfilter/locale\fr\LC_MESSAGES\tracspamfilter.po:1286: placeholders are incompatible
error: tracspamfilter/locale\fr\LC_MESSAGES\tracspamfilter.po:1291: placeholders are incompatible
catalog 'tracspamfilter/locale\\fr\\LC_MESSAGES\\tracspamfilter.po' contains errors, skipping
}}}

And even more coverage for the french translation (67%) ;-)