Use a proper NullTranslations instance instead of the class. This should fix errors of this kind:
TypeError: unbound method ugettext() must be called with NullTranslations
instance as first argument (got str instance instead)

See: #5958
Fix supplied by Shun-ichi Goto