1.2dev: Fix regression in r14707
The regression resulted in: 
`AttributeError: 'FakeSession' object has no attribute 'as_int'`
when `FakeSession` was returned by the `Request` object.

* Added `SessionDict` class, which `DetachedSession` and
  `FakeSession` inherit from.
* Added `cookie` kw arg to `MockRequest` object.

Refs #12561.